language: python
sudo: false
python:
- '3.4'
install: gem install crowdin-cli && pip install -r etc/requirements.txt
script:
- "./etc/build.sh"
notifications:
  email: false
env:
  global:
    secure: RIbu9atbeMJiEJM8xIGIWpaZl5rda5E3PJm+LvXa05CQWk7bv0k5a2ZzWGOI83xW2rj/eML8i/BDT/RN00++2HlwOFhp6VJN8ck/8R+0OuOpCzow45GIT/2x++IgRfJXqOQL4pQ1N8lqSxFLjpPexT5nOYSHgr+9DY6WFtokocw=
