name: main

on:
  push:
#   branches: [ stable, release-* ]
    branches: [ '*' ]

jobs:
  build-n-upload-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Setup Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: Test build
      run: sphinx-build -W -d build/doctrees source build/html

    - name: Build translation files
      run: sphinx-build -W -q -b gettext source build/locale

    - name: Set crowdin branch
      run: |
          echo "Ref: $GITHUB_REF"
          TESTREF=refs/heads/release-6.0.0
          BRANCH=${TESTREF##*/}
          echo "Branch: $BRANCH"
          VERSION="${BRANCH##*-}"
          if [[ "$VERSION" != "stable" ]]; then 
            echo "Using crowdin directory: $VERSION"
            echo "CROWDIN_BRANCH=$VERSION" >> $GITHUB_ENV 
          else
            echo "Using crowdin root directory"
            echo "CROWDIN_BRANCH=" >> $GITHUB_ENV
          fi
    - name: Upload to crowdin
      uses: crowdin/github-action@1.0.10
      with:
        crowdin_branch_name: ${{ env.CROWDIN_BRANCH }} 
        config: 'crowdin.yaml'
        dryrun_action: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
